branches:
 - master
language:
 - c++
compiler:
 - gcc
os:
 - linux
install:
 - lsb_release -a
      && sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-add-repository -y ppa:beineri/opt-qt542
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8 libc6-i386 qt54tools qt54svg qt54webkit qt54script
      && export CXX="g++-4.8"
      && export CC="gcc-4.8";
script:
 - QTDIR="/opt/qt54"
      && PATH="$QTDIR/bin:$PATH"
      && qt54-env.sh 
      ;
 - qmake
 - make 

